In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("C:\\SparkCourse\\contest\\train_ctrUa4K.csv")

In [3]:
df.shape

(614, 13)

In [4]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [14]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [15]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [18]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [26]:
#unique will work on array only and NaN should either be removed or converted to str
np.unique(df['Gender'].astype(str).values)

array(['Female', 'Male'], dtype=object)

In [27]:
np.unique(df['Married'].astype(str).values)

array(['No', 'Yes'], dtype=object)

In [28]:
np.unique(df['Dependents'].astype(str).values)

array(['0', '1', '2', '3+'], dtype=object)

In [24]:
df.dropna(inplace=True)

In [25]:
df.shape

(480, 13)

In [29]:
np.unique(df['Education'].astype(str).values)

array(['Graduate', 'Not Graduate'], dtype=object)

In [30]:
np.unique(df['Self_Employed'].astype(str).values)

array(['No', 'Yes'], dtype=object)

In [34]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   

   Credit_History Property_Area Loan_Status  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y

In [35]:
df.drop(['Loan_ID'], axis=1, inplace=True)

In [36]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(y)

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,

In [38]:
X = pd.get_dummies(X)

In [40]:
X.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   

   Credit_History  Gender_Female  Gender_Male  Married_No  Married_Yes  \
1             1.0              0            1           0            1   
2             1.0              0            1           0            1   
3             1.0              0            1           0            1   
4             1.0              0            1           1            0   
5             1.0              0            1           0            1   

   Dependents_0  Dependents_1  Dependents_2  Dependents_3+  \
1             0             1             0              0   
2             1             0             0              0   
3             1             0             0              0   
4             1             0             0              0   
5             0             0             1              0   

   Education_Graduate  Education_Not Graduate  Self_Employed_No  \
1                   1                       0                 1   
2                   1                       0                 0   
3                   0                       1                 1   
4                   1                       0                 1   
5                   1                       0                 0   

   Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
1                  0                    1                        0   
2                  1                    0                        0   
3                  0                    0                        0   
4                  0                    0                        0   
5                  1                    0                        0   

   Property_Area_Urban  
1                    0  
2                    1  
3                    1  
4                    1  
5                    1

In [42]:
from sklearn.preprocessing import RobustScaler
rb = RobustScaler()

In [43]:
rb.fit_transform(X)

array([[ 0.24511215,  0.18795074,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [-0.29081676, -0.48130478, -0.88571429, ...,  0.        ,
         0.        ,  1.        ],
       [-0.43199323,  0.56518362, -0.11428571, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [ 1.42632247, -0.37479197,  1.78571429, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.26077021, -0.48130478,  0.84285714, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.24511215, -0.48130478,  0.07142857, ...,  0.        ,
         1.        ,  0.        ]])

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [129]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)

In [130]:
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [48]:
y_pred = classifier.predict(X_test)

In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[11 17]
 [ 1 67]]


0.8125

In [53]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 5 23]
 [10 58]]


0.65625

In [54]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 0 28]
 [ 0 68]]


0.7083333333333334

In [55]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[14 14]
 [ 8 60]]


0.7708333333333334

In [106]:
test_df = pd.read_csv('C:\\SparkCourse\\contest\\test_lAUu6dG.csv')

In [107]:
test_df.count().sort_values()

Credit_History       338
Self_Employed        344
Gender               356
Dependents           357
Loan_Amount_Term     361
LoanAmount           362
Loan_ID              367
Married              367
Education            367
ApplicantIncome      367
CoapplicantIncome    367
Property_Area        367
dtype: int64

In [108]:
Loan_ID = test_df.pop('Loan_ID')

In [109]:
test_df.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
dtype: object

In [111]:
num_cols = df.select_dtypes([np.int64,np.float64]).columns

In [113]:
np.array(num_cols)

array(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'], dtype=object)

In [110]:
test_df.replace('nan', np.nan)

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male     Yes          0      Graduate            No             5720   
1      Male     Yes          1      Graduate            No             3076   
2      Male     Yes          2      Graduate            No             5000   
3      Male     Yes          2      Graduate            No             2340   
4      Male      No          0  Not Graduate            No             3276   
5      Male     Yes          0  Not Graduate           Yes             2165   
6    Female      No          1  Not Graduate            No             2226   
7      Male     Yes          2  Not Graduate            No             3881   
8      Male     Yes          2      Graduate           NaN            13633   
9      Male      No          0  Not Graduate            No             2400   
10     Male      No          0  Not Graduate            No             3091   
11     Male     Yes          1      Graduate           NaN             2185   
12     Male      No         3+      Graduate            No             4166   
13     Male     Yes          2      Graduate           NaN            12173   
14   Female      No          0      Graduate            No             4666   
15     Male      No          1      Graduate            No             5667   
16     Male     Yes          2      Graduate            No             4583   
17     Male     Yes         3+      Graduate            No             3786   
18     Male     Yes          0      Graduate            No             9226   
19     Male      No          0      Graduate            No             1300   
20     Male     Yes          1  Not Graduate            No             1888   
21   Female      No         3+  Not Graduate            No             2083   
22      NaN      No          0      Graduate            No             3909   
23   Female      No          0  Not Graduate            No             3765   
24     Male     Yes          0      Graduate            No             5400   
25     Male      No          0      Graduate            No                0   
26     Male     Yes          2      Graduate            No             4363   
27     Male     Yes          0      Graduate            No             7500   
28     Male     Yes          0      Graduate            No             3772   
29     Male      No          0      Graduate            No             2942   
..      ...     ...        ...           ...           ...              ...   
337    Male     Yes          0      Graduate            No             2292   
338    Male     Yes          1      Graduate           Yes             2360   
339  Female      No          0      Graduate            No             4333   
340    Male     Yes          0      Graduate           Yes             2623   
341    Male      No          0      Graduate           Yes             3972   
342    Male     Yes         3+  Not Graduate            No             3522   
343    Male     Yes          1      Graduate            No             4700   
344    Male      No          0      Graduate            No             6858   
345    Male     Yes         3+      Graduate            No             8334   
346    Male     Yes          0      Graduate            No             3391   
347    Male      No          0  Not Graduate            No             2868   
348    Male     Yes          2  Not Graduate            No             3418   
349    Male     Yes          0      Graduate           Yes             2500   
350    Male     Yes          2      Graduate            No             8667   
351    Male      No          0      Graduate            No             2283   
352    Male     Yes          0      Graduate            No             5817   
353    Male     Yes          0      Graduate            No             5119   
354    Male     Yes         3+  Not Graduate            No             5316   
355    Male     Yes         3+      Graduate           

In [117]:
test_df['ApplicantIncome'].replace(np.nan, test_df['ApplicantIncome'].mean(), inplace=True)
test_df['CoapplicantIncome'].replace(np.nan, test_df['CoapplicantIncome'].mean(), inplace=True)
test_df['LoanAmount'].replace(np.nan, test_df['LoanAmount'].mean(), inplace=True)
test_df['Loan_Amount_Term'].replace(np.nan, test_df['Loan_Amount_Term'].mean(), inplace=True)
test_df['Credit_History'].replace(np.nan, test_df['Credit_History'].mean(), inplace=True)

In [102]:
test_df.select_dtypes(include=['float64','int64'])

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
5               2165               3422       152.0             360.0   
6               2226                  0        59.0             360.0   
7               3881                  0       147.0             360.0   
8              13633                  0       280.0             240.0   
9               2400               2400       123.0             360.0   
10              3091                  0        90.0             360.0   
11              2185               1516       162.0             360.0   
12              4166                  0        40.0             180.0   
13             12173                  0       166.0             360.0   
14              4666                  0       124.0             360.0   
15              5667                  0       131.0             360.0   
16              4583               2916       200.0             360.0   
17              3786                333       126.0             360.0   
18              9226               7916       300.0             360.0   
19              1300               3470       100.0             180.0   
20              1888               1620        48.0             360.0   
21              2083                  0        28.0             180.0   
22              3909                  0       101.0             360.0   
23              3765                  0       125.0             360.0   
24              5400               4380       290.0             360.0   
25                 0              24000       148.0             360.0   
26              4363               1250       140.0             360.0   
27              7500               3750       275.0             360.0   
28              3772                833        57.0             360.0   
29              2942               2382       125.0             180.0   
..               ...                ...         ...               ...   
337             2292               1558       119.0             360.0   
338             2360               3355        87.0             240.0   
339             4333               2333       162.0             360.0   
340             2623               4831       122.0             180.0   
341             3972               4275       187.0             360.0   
342             3522                  0        81.0             180.0   
343             4700                  0        80.0             360.0   
344             6858                  0       176.0             360.0   
345             8334                  0       260.0             360.0   
346             3391               1966       133.0             360.0   
347             2868                  0        70.0             360.0   
348             3418               1380       135.0             360.0   
349             2500                296       137.0             300.0   
350             8667                  0       254.0             360.0   
351             2283              15000       106.0             360.0   
352             5817                910       109.0             360.0   
353             5119               3769       120.0             360.0   
354             5316                187       158.0             180.0   
355             7603               1213       197.0             360.0   
356             3791               1936        85.0             360.0   
357             2500                  0        60.0             360.0   
358             3132                  0        76.0             360.0   
359             4000               2667       152.0            

In [61]:
from sklearn.impute import SimpleImputer

In [103]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [104]:
test_df = imputer.fit_transform(test_df.select_dtypes(include=['float64','int64']))

In [97]:
imputer1 = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [105]:
test_df = imputer1.fit_transform(test_df.select_dtypes(include=['object']))

AttributeError: 'numpy.ndarray' object has no attribute 'select_dtypes'

In [126]:
test_df.count().sort_values()

Gender               367
Married              367
Dependents           367
Education            367
Self_Employed        367
ApplicantIncome      367
CoapplicantIncome    367
LoanAmount           367
Loan_Amount_Term     367
Credit_History       367
Property_Area        367
dtype: int64

In [119]:
test_df['Self_Employed'].value_counts()

No     307
Yes     37
Name: Self_Employed, dtype: int64

In [120]:
test_df['Self_Employed'].replace(np.nan, 'No', inplace=True)

In [122]:
test_df['Gender'].value_counts()

Male      286
Female     70
Name: Gender, dtype: int64

In [123]:
test_df['Gender'].replace(np.nan, 'Male', inplace=True)

In [124]:
test_df['Dependents'].value_counts()

0     200
2      59
1      58
3+     40
Name: Dependents, dtype: int64

In [125]:
test_df['Dependents'].replace(np.nan, '0', inplace=True)

In [127]:
test_df = pd.get_dummies(test_df)

In [128]:
rb.fit_transform(test_df)

array([[ 0.88069217, -0.42172393, -0.28318584, ...,  0.        ,
         0.        ,  1.        ],
       [-0.32331512,  0.19543304,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.55282332,  0.31886443,  1.45132743, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-0.24408015,  0.39827196,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.55282332,  0.56284715,  0.56637168, ...,  1.        ,
         0.        ,  0.        ],
       [ 2.46539162, -0.42172393, -0.49557522, ...,  1.        ,
         0.        ,  0.        ]])

In [131]:
y_pred_test = classifier.predict(test_df)

In [144]:
type(pd.Series(y_pred_test))

pandas.core.series.Series

In [135]:
type(Loan_ID)

pandas.core.series.Series

In [147]:
df = pd.concat([Loan_ID, pd.Series(y_pred_test)], axis=1)

TypeError: concat() got an unexpected keyword argument 'columns'

In [148]:
df.head()

Loan_ID  0
0  LP001015  Y
1  LP001022  Y
2  LP001031  Y
3  LP001035  Y
4  LP001051  Y

In [150]:
df.to_csv("C:\\SparkCourse\\contest\\test_results.csv", sep=',', encoding='utf-8')

In [140]:
np.array(Loan_ID).reshape(len(Loan_ID),1)

array([['LP001015'],
       ['LP001022'],
       ['LP001031'],
       ['LP001035'],
       ['LP001051'],
       ['LP001054'],
       ['LP001055'],
       ['LP001056'],
       ['LP001059'],
       ['LP001067'],
       ['LP001078'],
       ['LP001082'],
       ['LP001083'],
       ['LP001094'],
       ['LP001096'],
       ['LP001099'],
       ['LP001105'],
       ['LP001107'],
       ['LP001108'],
       ['LP001115'],
       ['LP001121'],
       ['LP001124'],
       ['LP001128'],
       ['LP001135'],
       ['LP001149'],
       ['LP001153'],
       ['LP001163'],
       ['LP001169'],
       ['LP001174'],
       ['LP001176'],
       ['LP001177'],
       ['LP001183'],
       ['LP001185'],
       ['LP001187'],
       ['LP001190'],
       ['LP001203'],
       ['LP001208'],
       ['LP001210'],
       ['LP001211'],
       ['LP001219'],
       ['LP001220'],
       ['LP001221'],
       ['LP001226'],
       ['LP001230'],
       ['LP001231'],
       ['LP001232'],
       ['LP001237'],
       ['LP00

In [142]:
final_df = pd.DataFrame([np.array(Loan_ID).reshape(len(Loan_ID),1),np.array(y_pred_test).reshape(len(y_pred_test),1)], columns=['Loan_ID','Loan_Status'])

ValueError: Shape of passed values is (1, 2), indices imply (2, 2)